/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as AuthorsAuthorIdRouteImport } from './routes/authors.$authorId'
import { Route as AuthAuthorRouteImport } from './routes/auth.author'
import { Route as AuthAgentRouteImport } from './routes/auth.agent'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorIdRoute = AuthorsAuthorIdRouteImport.update({
  id: '/authors/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthorRoute = AuthAuthorRouteImport.update({
  id: '/auth/author',
  path: '/auth/author',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAgentRoute = AuthAgentRouteImport.update({
  id: '/auth/agent',
  path: '/auth/agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/agent': typeof AuthAgentRoute
  '/auth/author': typeof AuthAuthorRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/books/$bookId': typeof BooksBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/agent': typeof AuthAgentRoute
  '/auth/author': typeof AuthAuthorRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/books/$bookId': typeof BooksBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/agent': typeof AuthAgentRoute
  '/auth/author': typeof AuthAuthorRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/books/$bookId': typeof BooksBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/auth/agent'
    | '/auth/author'
    | '/authors/$authorId'
    | '/books/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/auth/agent'
    | '/auth/author'
    | '/authors/$authorId'
    | '/books/$bookId'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/auth/agent'
    | '/auth/author'
    | '/authors/$authorId'
    | '/books/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthAgentRoute: typeof AuthAgentRoute
  AuthAuthorRoute: typeof AuthAuthorRoute
  AuthorsAuthorIdRoute: typeof AuthorsAuthorIdRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$authorId': {
      id: '/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/author': {
      id: '/auth/author'
      path: '/auth/author'
      fullPath: '/auth/author'
      preLoaderRoute: typeof AuthAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/agent': {
      id: '/auth/agent'
      path: '/auth/agent'
      fullPath: '/auth/agent'
      preLoaderRoute: typeof AuthAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthAgentRoute: AuthAgentRoute,
  AuthAuthorRoute: AuthAuthorRoute,
  AuthorsAuthorIdRoute: AuthorsAuthorIdRoute,
  BooksBookIdRoute: BooksBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
